CREATE DATABASE tasa Cambiodb
CREATE SCHEMA public AUTHORIZATION pg_database_owner;

COMMENT ON SCHEMA public IS 'standard public schema';

CREATE TABLE public."__EFMigrationsHistory" (
	"MigrationId" varchar(150) NOT NULL,
	"ProductVersion" varchar(32) NOT NULL,
	CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);
CREATE TABLE public.bitacora_tasa_cambio (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	fecha_consulta timestamp NOT NULL,
	fecha_tipo_cambio date NOT NULL,
	tipo_cambio numeric(18, 6) NOT NULL,
	origen_api varchar(200) NULL,
	CONSTRAINT "PK_bitacora_tasa_cambio" PRIMARY KEY (id)
);