// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace TipoCambioMoneda.Migrations
{
    [DbContext(typeof(TasaCambioDBContext))]
    partial class TasaCambioDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BitacoraTasaCambio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaConsulta")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_consulta");

                    b.Property<DateTime>("FechaTipoCambio")
                        .HasColumnType("date")
                        .HasColumnName("fecha_tipo_cambio");

                    b.Property<string>("OrigenApi")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("origen_api");

                    b.Property<decimal>("TipoCambio")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("tipo_cambio");

                    b.HasKey("Id");

                    b.ToTable("bitacora_tasa_cambio");
                });
#pragma warning restore 612, 618
        }
    }
}
