//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TipoCambioReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfoVariable", Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class InfoVariable : object
    {
        
        private TipoCambioReference.Variable[] VariablesField;
        
        private TipoCambioReference.Var[] CambioDiaField;
        
        private TipoCambioReference.VarDolar[] CambioDolarField;
        
        private int TotalItemsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public TipoCambioReference.Variable[] Variables
        {
            get
            {
                return this.VariablesField;
            }
            set
            {
                this.VariablesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public TipoCambioReference.Var[] CambioDia
        {
            get
            {
                return this.CambioDiaField;
            }
            set
            {
                this.CambioDiaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public TipoCambioReference.VarDolar[] CambioDolar
        {
            get
            {
                return this.CambioDolarField;
            }
            set
            {
                this.CambioDolarField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int TotalItems
        {
            get
            {
                return this.TotalItemsField;
            }
            set
            {
                this.TotalItemsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Variable", Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class Variable : object
    {
        
        private int monedaField;
        
        private string descripcionField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int moneda
        {
            get
            {
                return this.monedaField;
            }
            set
            {
                this.monedaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string descripcion
        {
            get
            {
                return this.descripcionField;
            }
            set
            {
                this.descripcionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Var", Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class Var : object
    {
        
        private int monedaField;
        
        private string fechaField;
        
        private float ventaField;
        
        private float compraField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int moneda
        {
            get
            {
                return this.monedaField;
            }
            set
            {
                this.monedaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fecha
        {
            get
            {
                return this.fechaField;
            }
            set
            {
                this.fechaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public float venta
        {
            get
            {
                return this.ventaField;
            }
            set
            {
                this.ventaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public float compra
        {
            get
            {
                return this.compraField;
            }
            set
            {
                this.compraField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VarDolar", Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class VarDolar : object
    {
        
        private string fechaField;
        
        private float referenciaField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string fecha
        {
            get
            {
                return this.fechaField;
            }
            set
            {
                this.fechaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public float referencia
        {
            get
            {
                return this.referenciaField;
            }
            set
            {
                this.referenciaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataVariable", Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class DataVariable : object
    {
        
        private TipoCambioReference.Var[] VarsField;
        
        private int TotalItemsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public TipoCambioReference.Var[] Vars
        {
            get
            {
                return this.VarsField;
            }
            set
            {
                this.VarsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int TotalItems
        {
            get
            {
                return this.TotalItemsField;
            }
            set
            {
                this.TotalItemsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/", ConfigurationName="TipoCambioReference.TipoCambioSoap")]
    public interface TipoCambioSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/VariablesDisponibles", ReplyAction="*")]
        System.Threading.Tasks.Task<TipoCambioReference.VariablesDisponiblesResponse> VariablesDisponiblesAsync(TipoCambioReference.VariablesDisponiblesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/Variables", ReplyAction="*")]
        System.Threading.Tasks.Task<TipoCambioReference.VariablesResponse> VariablesAsync(TipoCambioReference.VariablesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioFechaInicial", ReplyAction="*")]
        System.Threading.Tasks.Task<TipoCambioReference.TipoCambioFechaInicialResponse> TipoCambioFechaInicialAsync(TipoCambioReference.TipoCambioFechaInicialRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioRango", ReplyAction="*")]
        System.Threading.Tasks.Task<TipoCambioReference.TipoCambioRangoResponse> TipoCambioRangoAsync(TipoCambioReference.TipoCambioRangoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioFechaInicialMoneda", ReplyAction="*")]
        System.Threading.Tasks.Task<TipoCambioReference.TipoCambioFechaInicialMonedaResponse> TipoCambioFechaInicialMonedaAsync(TipoCambioReference.TipoCambioFechaInicialMonedaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioRangoMoneda", ReplyAction="*")]
        System.Threading.Tasks.Task<TipoCambioReference.TipoCambioRangoMonedaResponse> TipoCambioRangoMonedaAsync(TipoCambioReference.TipoCambioRangoMonedaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioDia", ReplyAction="*")]
        System.Threading.Tasks.Task<TipoCambioReference.TipoCambioDiaResponse> TipoCambioDiaAsync(TipoCambioReference.TipoCambioDiaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioDiaString", ReplyAction="*")]
        System.Threading.Tasks.Task<TipoCambioReference.TipoCambioDiaStringResponse> TipoCambioDiaStringAsync(TipoCambioReference.TipoCambioDiaStringRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VariablesDisponiblesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VariablesDisponibles", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public TipoCambioReference.VariablesDisponiblesRequestBody Body;
        
        public VariablesDisponiblesRequest()
        {
        }
        
        public VariablesDisponiblesRequest(TipoCambioReference.VariablesDisponiblesRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class VariablesDisponiblesRequestBody
    {
        
        public VariablesDisponiblesRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VariablesDisponiblesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VariablesDisponiblesResponse", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public TipoCambioReference.VariablesDisponiblesResponseBody Body;
        
        public VariablesDisponiblesResponse()
        {
        }
        
        public VariablesDisponiblesResponse(TipoCambioReference.VariablesDisponiblesResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class VariablesDisponiblesResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TipoCambioReference.InfoVariable VariablesDisponiblesResult;
        
        public VariablesDisponiblesResponseBody()
        {
        }
        
        public VariablesDisponiblesResponseBody(TipoCambioReference.InfoVariable VariablesDisponiblesResult)
        {
            this.VariablesDisponiblesResult = VariablesDisponiblesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VariablesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Variables", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public TipoCambioReference.VariablesRequestBody Body;
        
        public VariablesRequest()
        {
        }
        
        public VariablesRequest(TipoCambioReference.VariablesRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class VariablesRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int variable;
        
        public VariablesRequestBody()
        {
        }
        
        public VariablesRequestBody(int variable)
        {
            this.variable = variable;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VariablesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VariablesResponse", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public TipoCambioReference.VariablesResponseBody Body;
        
        public VariablesResponse()
        {
        }
        
        public VariablesResponse(TipoCambioReference.VariablesResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class VariablesResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TipoCambioReference.InfoVariable VariablesResult;
        
        public VariablesResponseBody()
        {
        }
        
        public VariablesResponseBody(TipoCambioReference.InfoVariable VariablesResult)
        {
            this.VariablesResult = VariablesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioFechaInicialRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioFechaInicial", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public TipoCambioReference.TipoCambioFechaInicialRequestBody Body;
        
        public TipoCambioFechaInicialRequest()
        {
        }
        
        public TipoCambioFechaInicialRequest(TipoCambioReference.TipoCambioFechaInicialRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioFechaInicialRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fechainit;
        
        public TipoCambioFechaInicialRequestBody()
        {
        }
        
        public TipoCambioFechaInicialRequestBody(string fechainit)
        {
            this.fechainit = fechainit;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioFechaInicialResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioFechaInicialResponse", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public TipoCambioReference.TipoCambioFechaInicialResponseBody Body;
        
        public TipoCambioFechaInicialResponse()
        {
        }
        
        public TipoCambioFechaInicialResponse(TipoCambioReference.TipoCambioFechaInicialResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioFechaInicialResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TipoCambioReference.DataVariable TipoCambioFechaInicialResult;
        
        public TipoCambioFechaInicialResponseBody()
        {
        }
        
        public TipoCambioFechaInicialResponseBody(TipoCambioReference.DataVariable TipoCambioFechaInicialResult)
        {
            this.TipoCambioFechaInicialResult = TipoCambioFechaInicialResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioRangoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioRango", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public TipoCambioReference.TipoCambioRangoRequestBody Body;
        
        public TipoCambioRangoRequest()
        {
        }
        
        public TipoCambioRangoRequest(TipoCambioReference.TipoCambioRangoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioRangoRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fechainit;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fechafin;
        
        public TipoCambioRangoRequestBody()
        {
        }
        
        public TipoCambioRangoRequestBody(string fechainit, string fechafin)
        {
            this.fechainit = fechainit;
            this.fechafin = fechafin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioRangoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioRangoResponse", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public TipoCambioReference.TipoCambioRangoResponseBody Body;
        
        public TipoCambioRangoResponse()
        {
        }
        
        public TipoCambioRangoResponse(TipoCambioReference.TipoCambioRangoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioRangoResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TipoCambioReference.DataVariable TipoCambioRangoResult;
        
        public TipoCambioRangoResponseBody()
        {
        }
        
        public TipoCambioRangoResponseBody(TipoCambioReference.DataVariable TipoCambioRangoResult)
        {
            this.TipoCambioRangoResult = TipoCambioRangoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioFechaInicialMonedaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioFechaInicialMoneda", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public TipoCambioReference.TipoCambioFechaInicialMonedaRequestBody Body;
        
        public TipoCambioFechaInicialMonedaRequest()
        {
        }
        
        public TipoCambioFechaInicialMonedaRequest(TipoCambioReference.TipoCambioFechaInicialMonedaRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioFechaInicialMonedaRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fechainit;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int moneda;
        
        public TipoCambioFechaInicialMonedaRequestBody()
        {
        }
        
        public TipoCambioFechaInicialMonedaRequestBody(string fechainit, int moneda)
        {
            this.fechainit = fechainit;
            this.moneda = moneda;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioFechaInicialMonedaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioFechaInicialMonedaResponse", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public TipoCambioReference.TipoCambioFechaInicialMonedaResponseBody Body;
        
        public TipoCambioFechaInicialMonedaResponse()
        {
        }
        
        public TipoCambioFechaInicialMonedaResponse(TipoCambioReference.TipoCambioFechaInicialMonedaResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioFechaInicialMonedaResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TipoCambioReference.DataVariable TipoCambioFechaInicialMonedaResult;
        
        public TipoCambioFechaInicialMonedaResponseBody()
        {
        }
        
        public TipoCambioFechaInicialMonedaResponseBody(TipoCambioReference.DataVariable TipoCambioFechaInicialMonedaResult)
        {
            this.TipoCambioFechaInicialMonedaResult = TipoCambioFechaInicialMonedaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioRangoMonedaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioRangoMoneda", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public TipoCambioReference.TipoCambioRangoMonedaRequestBody Body;
        
        public TipoCambioRangoMonedaRequest()
        {
        }
        
        public TipoCambioRangoMonedaRequest(TipoCambioReference.TipoCambioRangoMonedaRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioRangoMonedaRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fechainit;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fechafin;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int moneda;
        
        public TipoCambioRangoMonedaRequestBody()
        {
        }
        
        public TipoCambioRangoMonedaRequestBody(string fechainit, string fechafin, int moneda)
        {
            this.fechainit = fechainit;
            this.fechafin = fechafin;
            this.moneda = moneda;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioRangoMonedaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioRangoMonedaResponse", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public TipoCambioReference.TipoCambioRangoMonedaResponseBody Body;
        
        public TipoCambioRangoMonedaResponse()
        {
        }
        
        public TipoCambioRangoMonedaResponse(TipoCambioReference.TipoCambioRangoMonedaResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioRangoMonedaResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TipoCambioReference.DataVariable TipoCambioRangoMonedaResult;
        
        public TipoCambioRangoMonedaResponseBody()
        {
        }
        
        public TipoCambioRangoMonedaResponseBody(TipoCambioReference.DataVariable TipoCambioRangoMonedaResult)
        {
            this.TipoCambioRangoMonedaResult = TipoCambioRangoMonedaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioDiaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioDia", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public TipoCambioReference.TipoCambioDiaRequestBody Body;
        
        public TipoCambioDiaRequest()
        {
        }
        
        public TipoCambioDiaRequest(TipoCambioReference.TipoCambioDiaRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TipoCambioDiaRequestBody
    {
        
        public TipoCambioDiaRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioDiaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioDiaResponse", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public TipoCambioReference.TipoCambioDiaResponseBody Body;
        
        public TipoCambioDiaResponse()
        {
        }
        
        public TipoCambioDiaResponse(TipoCambioReference.TipoCambioDiaResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioDiaResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TipoCambioReference.InfoVariable TipoCambioDiaResult;
        
        public TipoCambioDiaResponseBody()
        {
        }
        
        public TipoCambioDiaResponseBody(TipoCambioReference.InfoVariable TipoCambioDiaResult)
        {
            this.TipoCambioDiaResult = TipoCambioDiaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioDiaStringRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioDiaString", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public TipoCambioReference.TipoCambioDiaStringRequestBody Body;
        
        public TipoCambioDiaStringRequest()
        {
        }
        
        public TipoCambioDiaStringRequest(TipoCambioReference.TipoCambioDiaStringRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TipoCambioDiaStringRequestBody
    {
        
        public TipoCambioDiaStringRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioDiaStringResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioDiaStringResponse", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public TipoCambioReference.TipoCambioDiaStringResponseBody Body;
        
        public TipoCambioDiaStringResponse()
        {
        }
        
        public TipoCambioDiaStringResponse(TipoCambioReference.TipoCambioDiaStringResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioDiaStringResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TipoCambioDiaStringResult;
        
        public TipoCambioDiaStringResponseBody()
        {
        }
        
        public TipoCambioDiaStringResponseBody(string TipoCambioDiaStringResult)
        {
            this.TipoCambioDiaStringResult = TipoCambioDiaStringResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface TipoCambioSoapChannel : TipoCambioReference.TipoCambioSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class TipoCambioSoapClient : System.ServiceModel.ClientBase<TipoCambioReference.TipoCambioSoap>, TipoCambioReference.TipoCambioSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public TipoCambioSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(TipoCambioSoapClient.GetBindingForEndpoint(endpointConfiguration), TipoCambioSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TipoCambioSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(TipoCambioSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TipoCambioSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(TipoCambioSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TipoCambioSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TipoCambioReference.VariablesDisponiblesResponse> TipoCambioReference.TipoCambioSoap.VariablesDisponiblesAsync(TipoCambioReference.VariablesDisponiblesRequest request)
        {
            return base.Channel.VariablesDisponiblesAsync(request);
        }
        
        public System.Threading.Tasks.Task<TipoCambioReference.VariablesDisponiblesResponse> VariablesDisponiblesAsync()
        {
            TipoCambioReference.VariablesDisponiblesRequest inValue = new TipoCambioReference.VariablesDisponiblesRequest();
            inValue.Body = new TipoCambioReference.VariablesDisponiblesRequestBody();
            return ((TipoCambioReference.TipoCambioSoap)(this)).VariablesDisponiblesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TipoCambioReference.VariablesResponse> TipoCambioReference.TipoCambioSoap.VariablesAsync(TipoCambioReference.VariablesRequest request)
        {
            return base.Channel.VariablesAsync(request);
        }
        
        public System.Threading.Tasks.Task<TipoCambioReference.VariablesResponse> VariablesAsync(int variable)
        {
            TipoCambioReference.VariablesRequest inValue = new TipoCambioReference.VariablesRequest();
            inValue.Body = new TipoCambioReference.VariablesRequestBody();
            inValue.Body.variable = variable;
            return ((TipoCambioReference.TipoCambioSoap)(this)).VariablesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TipoCambioReference.TipoCambioFechaInicialResponse> TipoCambioReference.TipoCambioSoap.TipoCambioFechaInicialAsync(TipoCambioReference.TipoCambioFechaInicialRequest request)
        {
            return base.Channel.TipoCambioFechaInicialAsync(request);
        }
        
        public System.Threading.Tasks.Task<TipoCambioReference.TipoCambioFechaInicialResponse> TipoCambioFechaInicialAsync(string fechainit)
        {
            TipoCambioReference.TipoCambioFechaInicialRequest inValue = new TipoCambioReference.TipoCambioFechaInicialRequest();
            inValue.Body = new TipoCambioReference.TipoCambioFechaInicialRequestBody();
            inValue.Body.fechainit = fechainit;
            return ((TipoCambioReference.TipoCambioSoap)(this)).TipoCambioFechaInicialAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TipoCambioReference.TipoCambioRangoResponse> TipoCambioReference.TipoCambioSoap.TipoCambioRangoAsync(TipoCambioReference.TipoCambioRangoRequest request)
        {
            return base.Channel.TipoCambioRangoAsync(request);
        }
        
        public System.Threading.Tasks.Task<TipoCambioReference.TipoCambioRangoResponse> TipoCambioRangoAsync(string fechainit, string fechafin)
        {
            TipoCambioReference.TipoCambioRangoRequest inValue = new TipoCambioReference.TipoCambioRangoRequest();
            inValue.Body = new TipoCambioReference.TipoCambioRangoRequestBody();
            inValue.Body.fechainit = fechainit;
            inValue.Body.fechafin = fechafin;
            return ((TipoCambioReference.TipoCambioSoap)(this)).TipoCambioRangoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TipoCambioReference.TipoCambioFechaInicialMonedaResponse> TipoCambioReference.TipoCambioSoap.TipoCambioFechaInicialMonedaAsync(TipoCambioReference.TipoCambioFechaInicialMonedaRequest request)
        {
            return base.Channel.TipoCambioFechaInicialMonedaAsync(request);
        }
        
        public System.Threading.Tasks.Task<TipoCambioReference.TipoCambioFechaInicialMonedaResponse> TipoCambioFechaInicialMonedaAsync(string fechainit, int moneda)
        {
            TipoCambioReference.TipoCambioFechaInicialMonedaRequest inValue = new TipoCambioReference.TipoCambioFechaInicialMonedaRequest();
            inValue.Body = new TipoCambioReference.TipoCambioFechaInicialMonedaRequestBody();
            inValue.Body.fechainit = fechainit;
            inValue.Body.moneda = moneda;
            return ((TipoCambioReference.TipoCambioSoap)(this)).TipoCambioFechaInicialMonedaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TipoCambioReference.TipoCambioRangoMonedaResponse> TipoCambioReference.TipoCambioSoap.TipoCambioRangoMonedaAsync(TipoCambioReference.TipoCambioRangoMonedaRequest request)
        {
            return base.Channel.TipoCambioRangoMonedaAsync(request);
        }
        
        public System.Threading.Tasks.Task<TipoCambioReference.TipoCambioRangoMonedaResponse> TipoCambioRangoMonedaAsync(string fechainit, string fechafin, int moneda)
        {
            TipoCambioReference.TipoCambioRangoMonedaRequest inValue = new TipoCambioReference.TipoCambioRangoMonedaRequest();
            inValue.Body = new TipoCambioReference.TipoCambioRangoMonedaRequestBody();
            inValue.Body.fechainit = fechainit;
            inValue.Body.fechafin = fechafin;
            inValue.Body.moneda = moneda;
            return ((TipoCambioReference.TipoCambioSoap)(this)).TipoCambioRangoMonedaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TipoCambioReference.TipoCambioDiaResponse> TipoCambioReference.TipoCambioSoap.TipoCambioDiaAsync(TipoCambioReference.TipoCambioDiaRequest request)
        {
            return base.Channel.TipoCambioDiaAsync(request);
        }
        
        public System.Threading.Tasks.Task<TipoCambioReference.TipoCambioDiaResponse> TipoCambioDiaAsync()
        {
            TipoCambioReference.TipoCambioDiaRequest inValue = new TipoCambioReference.TipoCambioDiaRequest();
            inValue.Body = new TipoCambioReference.TipoCambioDiaRequestBody();
            return ((TipoCambioReference.TipoCambioSoap)(this)).TipoCambioDiaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TipoCambioReference.TipoCambioDiaStringResponse> TipoCambioReference.TipoCambioSoap.TipoCambioDiaStringAsync(TipoCambioReference.TipoCambioDiaStringRequest request)
        {
            return base.Channel.TipoCambioDiaStringAsync(request);
        }
        
        public System.Threading.Tasks.Task<TipoCambioReference.TipoCambioDiaStringResponse> TipoCambioDiaStringAsync()
        {
            TipoCambioReference.TipoCambioDiaStringRequest inValue = new TipoCambioReference.TipoCambioDiaStringRequest();
            inValue.Body = new TipoCambioReference.TipoCambioDiaStringRequestBody();
            return ((TipoCambioReference.TipoCambioSoap)(this)).TipoCambioDiaStringAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TipoCambioSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.TipoCambioSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TipoCambioSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://www.banguat.gob.gt/variables/ws/TipoCambio.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.TipoCambioSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://www.banguat.gob.gt/variables/ws/TipoCambio.asmx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            TipoCambioSoap,
            
            TipoCambioSoap12,
        }
    }
}
